CREATE TABLE PLAYER (ID NUMBER(3)  PRIMARY KEY , NAME VARCHAR2(25) UNIQUE, AGE NUMBER(2));
CREATE TABLE MANAGER (ID NUMBER(3)  ,NAME VARCHAR2(25), SALARY NUMBER(6) , CONSTRAINT mgr_composite_unique UNIQUE (ID , NAME) );
CREATE TABLE MANAGER_2 (ID NUMBER(3) PRIMARY KEY , NAME VARCHAR2(25) , AGE NUMBER(2));
