DROP TABLE STUDENTS;
CREATE TABLE STUDENTS (NAME VARCHAR2(255) , MARKS NUMBER(3));
INSERT INTO STUDENTS VALUES ('AHMED' , 95);
INSERT INTO STUDENTS VALUES ('ESLAM' , 90);
INSERT INTO STUDENTS VALUES ('ALI' , 80);
INSERT INTO STUDENTS VALUES ('MONA' , 70);
INSERT INTO STUDENTS VALUES ('MOHAMED' , 50);
SELECT NAME, MARKS,
       DECODE(TRUNC(MARKS / 10), 
              10, 'A', 
              9,  'A', 
              8,  'B' ,
              7,  'C',
              'F') AS GRADE
FROM STUDENTS;

CREATE TABLE ORDERS (STATUS VARCHAR2(10));
INSERT INTO ORDERS VALUES ('P');
INSERT INTO ORDERS VALUES ('S');
INSERT INTO ORDERS VALUES ('D');

SELECT STATUS , DECODE (STATUS , 'P' ,'PENDING' ,'S' ,'SHIPPED' ,'D' ,'DELIVERD' )AS FULL_STATUS FROM ORDERS;