DROP TABLE STUDENTS;
CREATE TABLE STUDENTS (NAME VARCHAR2(255) , MARKS NUMBER(3));
INSERT INTO STUDENTS VALUES ('AHMED' , 95);
INSERT INTO STUDENTS VALUES ('ESLAM' , 90);
INSERT INTO STUDENTS VALUES ('ALI' , 80);
INSERT INTO STUDENTS VALUES ('MONA' , 70);
INSERT INTO STUDENTS VALUES ('MOHAMED' , 50);
SELECT NAME , MARKS, CASE
	WHEN MARKS >=90 THEN 'A'
	WHEN MARKS BETWEEN 80 AND 89 THEN 'B'
	WHEN MARKS BETWEEN 70 AND 79 THEN 'C'
	ELSE 'F'
	END "GRADE"
FROM STUDENTS;