SELECT REPLACE ('database' , 'a' , '@') FROM DUAL;
SELECT REPLACE ('old' , 'old' , 'new') FROM DUAL;
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT (PRODUCT_NAME VARCHAR2(255));
INSERT INTO PRODUCT VALUES ('CHICKEN');
INSERT INTO PRODUCT VALUES ('MEAT');
INSERT INTO PRODUCT VALUES ('CHEESE');
SELECT LPAD (PRODUCT_NAME , 15 , '*')FROM PRODUCT;
SELECT RPAD (PRODUCT_NAME , 15 , '#')FROM PRODUCT;



