DROP TABLE EMP_TEST ;
CREATE TABLE EMP_TEST (NAME    VARCHAR2(255));
INSERT INTO EMP_TEST VALUES ('    AHMED            ');
INSERT INTO EMP_TEST VALUES ('****AHMED*****');
SELECT TRIM(NAME) TRM FROM EMP_TEST; 
SELECT lTRIM(NAME) TRM FROM EMP_TEST;
SELECT RTRIM(NAME) TRM FROM EMP_TEST;
SELECT TRIM('*' FROM NAME) TRM FROM EMP_TEST;
