CREATE TABLE MANAGER(id  NUMBER(3) NOT NULL
                   , name  VARCHAR2(255)  
                   , age  NUMBER(3) 
                   , birth_date  DATE  
                   , address  VARCHAR2(255));


ALTER TABLE MANAGER DROP (address);

ALTER TABLE MANAGER ADD (city_address  VARCHAR2(255), street   VARCHAR2(255));

ALTER TABLE MANAGER RENAME COLUMN  name TO full_name;

ALTER TABLE MANAGER READ ONLY;

CREATE TABLE OWNER (ID , NAME , BIRTHDATE) AS SELECT ID , FULL_NAME , BIRTH_DATE FROM MANAGER;

ALTER TABLE MANAGER RENAME TO MASTER;

DROP TABLE MASTER;
DROP TABLE OWNER;