
CREATE TABLE DOCTOR (ID NUMBER(3) , NAME VARCHAR2(255) , SALARY  NUMBER(6) , ADDRESS VARCHAR2(255));
INSERT INTO DOCTOR 
VALUES (1 , 'AHMED' , 10000 , 'ALEX');
INSERT INTO DOCTOR 
VALUES (2 , 'Eslam' , 12000 , 'CAIRO');
INSERT INTO DOCTOR 
VALUES (3 , 'MOHAMED' , 14000 , 'ALEX');
INSERT INTO DOCTOR 
VALUES (4 , 'ALI' , 16000 , 'CAIRO');
INSERT INTO DOCTOR 
VALUES (5 , 'MONA' , 18000 , 'ALEX');
INSERT INTO DOCTOR 
VALUES (6 , 'AYA' , 20000 , 'CAIRO');
INSERT INTO DOCTOR 
VALUES (7 , 'ASMAA' , 22000 , 'ALEX');
INSERT INTO DOCTOR 
VALUES (8 , 'RANA' , 1000 , 'CAIRO');
INSERT INTO DOCTOR 
VALUES (9 , 'ZIAD' , 2000 , 'ALEX');
INSERT INTO DOCTOR 
VALUES (10 , 'OMAR' , 3000 , 'CAIRO');

UPDATE DOCTOR 
SET SALARY = 20000
WHERE ID = 3;

DELETE DOCTOR WHERE ID = 9;

SELECT NAME  || SALARY AS "NAME_WITH_SALARY" FROM DOCTOR;

SELECT ID , NAME , SALARY*2 , ADDRESS FROM DOCTOR;
SELECT * FROM DOCTOR WHERE SALARY IN (1000 , 2000 , 3000);

ALTER TABLE DOCTOR RENAME TO PRD_DOCTOR;

